#NAME
name: Push images to Dockerhub and deploy on ELastic Beanstalk
#EVENT
on:
  push:
    branches:
      - main
#JOBS
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Create .env file
      - name: Create env file
        run: |
          touch .env.prod
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env.prod
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env.prod
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env.prod
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env.prod
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env.prod
          echo JWT_ACCESS_TOKEN_SECRET=${{ secrets.JWT_ACCESS_TOKEN_SECRET }} >> .env.prod
          cat .env.prod

      - name: Checkout Latest repo
        run: zip -r deploy.zip ./* -x ./node_modeules

      - name: Get Timestemp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'

      # Deploy to Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.ENVIRONMENT_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: '${{ steps.current-time.outputs.time }}'
          deployment_package: deploy.zip
          wait_for_deployment: false
          wait_for_environment_recovery: 100
